version: '3'

services:
  backend:
    build:
      context: ./portfolio-backend
      dockerfile: /Users/kiranun/Desktop/Full Stack Practice/portfolio_backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./portfolio
      dockerfile: /Users/kiranun/Desktop/Full Stack Practice/portfolio/Dockerfile
    volumes:
      - build_folder:/frontend/build
    ports:
      - '3000:3000'
    stdin_open: true
volumes:
  build_folder: